name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-24.04-arm64
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build --release
        FILE_NAME="netutil-${{ github.ref_name }}-${{ matrix.arch }}"
        pwd
        find . -name "netutil"
        mv target/release/netutil FILE_NAME
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: build-${{ github.run_id }}
        files: |
          netutil-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
