name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu   
    - name: Release
      run: |
        pwd
        find . -name "netutil"
        gh release create ${{ github.ref_name }} \
          netutil/target/release/netutil --title "Relase ${{ github.ref_name }}" --notes "Auto Release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
